### ISSUE TITLE
Prompt not displaying properly (even with Powerline font)

### ISSUE THREAD

**Issue by swissChili** [tay1orjones/dotfiles#10]
Hello, I recently discovered your dotfiles and wanted to install them on my system. Everything is working fine for me, except that some of the characters are not displaying properly. I tried turning off emoji prompts, but this still occured. Some of the characters appear to be overlapping. I am using Hyper terminal by the way, with Droid Sans Mono Dotted for Powerline as my font. 

Do you have any idea why this is happening? Thank you in advance.

I am using High Sierra with the newest versions of Bash, Hyper, and your dotfiles. 

![screen shot 2018-03-10 at 12 35 27 pm](https://user-images.githubusercontent.com/26192527/37246539-ab439478-245f-11e8-8a6a-26c274a64b8e.png)

**Comment by tay1orjones** [comment]
Hey! 👋Thanks for bringing this to my attention. Unfortunately, this prompt proved to be way too riddled with bugs to use, as you've found 😅 

I've moved away from it to instead use a [slightly modified version](https://github.com/tay1orjones/dotfiles/blob/master/shell/.bash_prompt) of the [Pure prompt bash port](https://github.com/sindresorhus/pure#ports).
