### ISSUE TITLE
Font name used

### ISSUE THREAD

**Issue by bufface** [tay1orjones/dotfiles#9]
What font are you using? I can't see the same result in my Hyper Terminal.
<img width="510" alt="screen shot 2017-09-16 at 1 14 11 pm" src="https://user-images.githubusercontent.com/10931660/30513861-fc3383ba-9ae0-11e7-84d5-4c9ebf7250fe.png">

**Comment by tay1orjones** [comment]
@bufface _Droid Sans Mono Dotted for Powerline_ is what I'm using.

Any of the [powerline fonts](https://github.com/powerline/fonts) should work.
